config/routes.rb
Rails.application.routes.draw do
  resources :projects, format: false
  resources :tasks, format: false do
    collection do
      patch 'update_status'
    end
  end

end

app/models/priority.rb
class Priority < ActiveRecord::Base
  has_many :tasks
  default_scope { order(sequence: :asc)}
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :tasks
  default_scope { order(sequence: :asc)}
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :status
  belongs_to :priority
  belongs_to :project
  belongs_to :assign_user, class_name: 'User' ,foreign_key: :assign_user_id

  validates(:title, presence: true, length: { maximum: 100} )
  validates(:description, length: { maximum: 1000} )
  validates(:status_id, presence: true)
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks, foreign_key: :assign_user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    if @project.save!
      redirect_to @project, notice: 'プロジェクトを作成しました。'
    else
      render :new
    end
  end

  def update
    if @project.update!(project_params)
      redirect_to @project, notice: 'プロジェクトを更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :lock_version)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_combobox_data, only: [:new, :edit, :create, :update]

  # 全タスクを取得し、タスク一覧画面の html を返します。
  def index
    @tasks = Task.all
    @statuses = Status.all
  end

  # 指定した id のタスクを取得し、タスクの表示画面の html を返します。
  def show
    @task = get_task
  end

  # 新しいタスクのインスタンを生成し、タスクの登録画面の html を返します。
  def new
    @task = Task.new
  end

  # 指定した id のタスクを取得し、タスクの編集画面の html を返します。
  def edit
    @task = get_task
  end

  # 新しいタスクを登録します。
  # タスクの登録に成功した場合、タスクの表示画面へリダイレクトします。
  # タスクの登録に失敗した場合、タスクの登録画面の html を返します。
  def create
    @task = Task.new(task_params)

    unless @task.valid?
      render :new
      return
    end

    if @task.save!
      redirect_to @task, notice: 'タスクを作成しました。'
    else
      render :new
    end
  end

  # 指定した id のタスクを更新します。
  def update
    @task = get_task
    @task.attributes = task_params

    unless @task.valid?
      render :edit
      return
    end

    if @task.update!(task_params)
      redirect_to @task, notice: 'タスクを更新しました。'
    else
      render :edit
    end
  end

  # 指定した id のタスクを削除します。
  def destroy
    @task = get_task
    @task.destroy
    redirect_to tasks_url
  end

  # 一覧画面でチェックを入れたタスクを選択したステータスで更新します。
  def update_status

    if params.require(:task)[:status] == ''
      redirect_to tasks_path, notice: 'ステータスを選択してください'
      return
    end

    task_ids = params.require(:checked_tasks).select{|k,v| v == '1'}.keys
    task_ids.each do |task_id|
      task = Task.find(task_id)
      task.update_attribute(:status_id, params.require(:task)[:status])
    end

    redirect_to tasks_url
  end

  private

  # url で指定した id のタスクを取得します。
  # @return [Task] 指定した id のタスク
  def get_task
    Task.find(params[:id])
  end

  # 画面で入力したパラメータのハッシュを取得します。
  # @return [Hash] 画面で入力したパラメータ
  def task_params
    params.require(:task).permit(
      :title,
      :description,
      :status_id,
      :priority_id,
      :project_id,
      :assign_user_id,
      :lock_version)
  end

  # コンボボックスに設定するデータを取得します。
  def get_combobox_data
    @statuses = Status.all
    @priorities = Priority.all
    @projects = Project.all
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- メニュー -->
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container-fluid ">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarMain">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">タスク管理</a>
    </div>
    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="nav navbar-nav">  
        <li><a href="#">タスク</a></li>
          <ul class="dropdown-menu" role="menu">
            <li role="presentation"><a href="#">リンクのリスト１</a></li>
            <li role="presentation"><a href="#">リンクのリスト２</a></li>
            <li role="presentation"><a href="#">リンクのリスト３</a></li>
          </ul>
        <li><a href="#">プロジェクト</a></li>
        <li><a href="#">他にあれば・・・</a></li>
      </ul>
      <!-- todo ログイン画面に遷移 -->
      <button type="button" class="btn btn-default navbar-btn navbar-right">Sign in</button>
      <!-- todo ログイン状態により、出力メッセージを変更したい -->
      <p class="navbar-text navbar-right">ようこそ ゲスト さん。</p>
    </div>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= @project.errors.count.to_s + '件のエラーがあります。' %></h2>
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :lock_version %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>プロジェクトの編集</h1>
</div>
<%= render 'form' %>

<%= link_to '表示', @project %>
<%= link_to '戻る', projects_path %>

app/views/projects/index.html.erb
<div class="page-header">
  <h1>プロジェクト一覧</h1>
</div>

<div class="table-responsiv">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>プロジェクト名</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= link_to '表示', project %></td>
          <td><%= link_to '編集', edit_project_path(project) %></td>
          <td><%= link_to '削除', project, method: :delete, data: {confirm: '削除してもよろしいですか?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to '新プロジェクトの作成', new_project_path %>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>新プロジェクトの作成</h1>
</div>
<%= render 'form' %>

<%= link_to '戻る', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<P>
  <strong>Name:</strong>
  <%= @project.name %>
</P>

<%= link_to '編集', edit_project_path(@project) %> |
<%= link_to '戻る', projects_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
    <% if @task.errors.any? %>
        <div id="error_explanation">
          <h2><%= @task.errors.count.to_s + '件のエラーがあります' %></h2>
          <ul>
            <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, class: 'control-label' %>
      <%= f.text_field :title, class: 'form-control', maxlength: 100 %>
    </div>

    <div class="form-group">
      <%= f.label :description, class: 'control-label' %>
      <%= f.text_area :description, class: 'form-control', maxlength: 1000 , rows: 20 %>
    </div>

    <div class="form-group">
      <%= f.label :status_id, class: 'control-label' %>
      <%= f.collection_select(
                  :status_id, @statuses, :id, :name, {}, { class: 'form-control', selected: Settings.status[:untouched] }
          ) %>
    </div>

    <div class="form-group">
      <%= f.label :priority_id, class: 'control-label' %>
      <%= f.collection_select(
                  :priority_id, @priorities, :id, :name, { include_blank: true }, { class: 'form-control' }
          ) %>
    </div>

    <div class="form-group">
      <%= f.label :project_id, class: 'control-label' %>
      <%= f.collection_select(
                  :project_id, @projects, :id, :name, { include_blank: true }, { class: 'form-control' }
          ) %>
    </div>

    <div class="form-group">
      <%= f.label :assign_user_id, class: 'control-label' %>
      <%= f.collection_select(
                  :assign_user_id, @users, :id, :name, { include_blank: true }, { class: 'form-control' }
          ) %>
    </div>

    <%= f.submit class: 'btn btn-default'%>
<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
  <h1>タスクの編集</h1>
</div>
<%= render 'form' %>

<%= link_to '表示', @task %>
<%= link_to '戻る', tasks_path %>

app/views/tasks/index.html.erb
<div class="page-header">
  <h1>タスク一覧</h1>
</div>
<p id="notice"><%= notice %></p>

<%= form_tag({ action: 'update_status' }, { method: 'patch' }) do %>
<div class="table-responsiv">
  <table class="table table-striped table-hover">
    <thead>
      <th><input type="checkbox"></td></th>
      <th><%= t 'tasks.title' %></th>
      <th><%= t 'tasks.description' %></th>
      <th><%= t 'tasks.status_id' %></th>
      <th><%= t 'tasks.priority_id' %></th>
      <th><%= t 'tasks.project_id' %></th>
      <th><%= t 'tasks.assign_user_id' %></th>
      <th colspan="3"></th>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= check_box('checked_tasks', task.id)%></td>
          <td><%= task.title %></td>
          <td><span data-toggle="tooltip" title=<%= task.description %>><%= task.description %></span></td>
          <% unless task.status.nil? %>
              <td><%= task.status.name %></td>
          <% else %>
              <td></td>
          <% end %>
          <% unless task.priority.nil? %>
              <td><%= task.priority.name %></td>
          <% else %>
              <td></td>
          <% end %>
          <% unless task.project.nil? %>
              <td><%= task.project.name %></td>
          <% else %>
              <td></td>
          <% end %>
          <% unless task.assign_user.nil? %>
              <td><%= task.assign_user.name %></td>
          <% else %>
              <td></td>
          <% end %>
          <td><%= link_to '表示', task, {:class => "btn btn-primary btn-sm"} %></td>
          <td><%= link_to '編集', edit_task_path(task) %></td>
          <td><%= link_to '削除', task, method: :delete, data: {confirm: '削除してもいいですか?' }  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

    <p>
      <%= link_to '新タスクの登録', new_task_path ,{:class => "btn btn-primary"} %>
    </p>

    <div class="form-group">
      <%= collection_select(:task, :status, @statuses, :id, :name, { include_blank: true }, { class: 'form-control' }) %>
      <%= submit_tag 'スタータスの更新' %>
    </div>
<% end %>

app/views/tasks/new.html.erb
<div class="page-header">
  <h1>タスクの登録</h1>
</div>
<%= render 'form' %>

<%= link_to '戻る', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t 'tasks.title' %></strong>
  <%= @task.title %>
</p>

<p>
  <strong><%= t 'tasks.description' %></strong>
  <%= @task.description %>
</p>

<p>
  <strong><%= t 'tasks.status_id' %></strong>
  <% unless @task.status.nil? %>
      <%= @task.status.name %>
  <% end %>
</p>

<p>
  <strong><%= t 'tasks.priority_id' %></strong>
  <% unless @task.priority.nil? %>
      <%= @task.priority.name %>
  <% end %>
</p>

<p>
  <strong><%= t 'tasks.project_id' %></strong>
  <% unless @task.project.nil? %>
      <%= @task.project.name %>
  <% end %>
</p>

<p>
  <strong><%= t 'tasks.assign_user_id' %></strong>
  <% unless @task.assign_user.nil? %>
      <%= @task.assign_user.name %>
  <% end %>
</p>

<%= link_to '編集', edit_task_path(@task) %> |
<%= link_to '戻る', tasks_path %>